apiVersion: v2
name: learning-assistant
description: A comprehensive Personal Learning Assistant application with AI-powered features
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/learning-assistant
sources:
  - https://github.com/your-org/learning-assistant
maintainers:
  - name: DevOps Team
    email: devops@example.com
    url: https://example.com
keywords:
  - learning
  - education
  - ai
  - nextjs
  - kubernetes
  - postgresql
  - redis
annotations:
  category: Education
  licenses: MIT
  images: |
    - name: learning-assistant
      image: ghcr.io/learning-assistant/learning-assistant:1.0.0
    - name: postgres
      image: postgres:15-alpine
    - name: redis
      image: redis:7-alpine
    - name: nginx
      image: nginx:1.25-alpine
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: ingress-nginx
    version: 4.x.x
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
  - name: cert-manager
    version: 1.x.x
    repository: https://charts.jetstack.io
    condition: certManager.enabled
  - name: prometheus
    version: 25.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 7.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled