apiVersion: v1
kind: Namespace
metadata:
  name: learning-assistant
  labels:
    name: learning-assistant
    app.kubernetes.io/name: learning-assistant
    app.kubernetes.io/part-of: learning-platform
    app.kubernetes.io/managed-by: helm
    environment: production
  annotations:
    kubernetes.io/managed-by: "Enhanced CI/CD Pipeline"
    description: "Personal Learning Assistant application namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: learning-assistant-quota
  namespace: learning-assistant
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
    count/ingresses.networking.k8s.io: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: learning-assistant-limits
  namespace: learning-assistant
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: learning-assistant-netpol
  namespace: learning-assistant
spec:
  podSelector:
    matchLabels:
      app: learning-assistant
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: learning-assistant
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80