apiVersion: v2
name: microservice
description: A comprehensive Helm chart for deploying microservices with best practices
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservice
  - kubernetes
  - deployment
  - monitoring
  - security
home: https://github.com/your-org/microservice-chart
sources:
  - https://github.com/your-org/microservice-chart
maintainers:
  - name: DevOps Team
    email: devops@example.com
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
annotations:
  category: Application
  licenses: Apache-2.0