apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-assistant
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: learning-assistant
    app.kubernetes.io/instance: learning-assistant
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: learning-assistant
    app.kubernetes.io/managed-by: kubectl
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubernetes.io/change-cause: "Initial deployment"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # Zero downtime deployments
  selector:
    matchLabels:
      app.kubernetes.io/name: learning-assistant
      app.kubernetes.io/instance: learning-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: learning-assistant
        app.kubernetes.io/instance: learning-assistant
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: learning-assistant
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/api/metrics"
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: learning-assistant
        image: learning-assistant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: PORT
        - name: NEXT_TELEMETRY_DISABLED
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: NEXT_TELEMETRY_DISABLED
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: LOG_LEVEL
        - name: NODE_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: NODE_OPTIONS
        # Database configuration
        - name: DATABASE_URL
          value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: DATABASE_PASSWORD
        # Redis configuration
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: REDIS_PASSWORD
        # JWT and authentication
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: JWT_SECRET
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: NEXTAUTH_SECRET
        # External service API keys
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: OPENAI_API_KEY
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: SUPABASE_SERVICE_KEY
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: RESEND_API_KEY
        - name: TAMBO_API_KEY
          valueFrom:
            secretKeyRef:
              name: learning-assistant-secrets
              key: TAMBO_API_KEY
        # Feature flags
        - name: ENABLE_CHAT
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: ENABLE_CHAT
        - name: ENABLE_QUIZ
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: ENABLE_QUIZ
        - name: ENABLE_PROGRESS_TRACKING
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: ENABLE_PROGRESS_TRACKING
        - name: ENABLE_EMAIL
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: ENABLE_EMAIL
        # Monitoring
        - name: ENABLE_METRICS
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: ENABLE_METRICS
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              name: learning-assistant-config
              key: METRICS_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: app-logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir: {}
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "2"
        - name: edns0