apiVersion: v1
kind: ConfigMap
metadata:
  name: learning-assistant-config
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: learning-assistant
    app.kubernetes.io/instance: learning-assistant
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: learning-assistant
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  LOG_LEVEL: "info"
  PORT: "3000"
  # Database configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "learning_assistant_db"
  DATABASE_USER: "learning_user"
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  # Application configuration
  APP_NAME: "Personal Learning Assistant"
  APP_VERSION: "1.0.0"
  # Feature flags
  ENABLE_CHAT: "true"
  ENABLE_QUIZ: "true"
  ENABLE_PROGRESS_TRACKING: "true"
  ENABLE_EMAIL: "true"
  # Performance settings
  NODE_OPTIONS: "--max-old-space-size=1024"
  # Monitoring
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  # Security
  ENABLE_SECURITY_HEADERS: "true"
  ENABLE_RATE_LIMITING: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: learning-assistant
data:
  POSTGRES_DB: "learning_assistant_db"
  POSTGRES_USER: "learning_user"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: learning-assistant
data:
  redis.conf: |
    # Redis configuration for Learning Assistant
    
    # Memory and performance
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Persistence
    appendonly yes
    appendfsync everysec
    
    # Security
    requirepass ${REDIS_PASSWORD}
    
    # Networking
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    
    # Logging
    loglevel notice
    
    # Performance tuning
    tcp-keepalive 300
    timeout 0