apiVersion: v1
kind: Secret
metadata:
  name: learning-assistant-secrets
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: learning-assistant
    app.kubernetes.io/instance: learning-assistant
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: learning-assistant
type: Opaque
data:
  # Database credentials (base64 encoded)
  # Use: echo -n "your-password" | base64
  DATABASE_PASSWORD: ""  # Replace with base64 encoded password
  POSTGRES_PASSWORD: ""  # Replace with base64 encoded password
  
  # Redis credentials
  REDIS_PASSWORD: ""     # Replace with base64 encoded password
  
  # JWT secrets
  JWT_SECRET: ""         # Replace with base64 encoded JWT secret
  NEXTAUTH_SECRET: ""    # Replace with base64 encoded NextAuth secret
  
  # External service API keys
  OPENAI_API_KEY: ""     # Replace with base64 encoded OpenAI API key
  SUPABASE_SERVICE_KEY: ""  # Replace with base64 encoded Supabase service key
  RESEND_API_KEY: ""     # Replace with base64 encoded Resend API key
  TAMBO_API_KEY: ""      # Replace with base64 encoded Tambo API key
  
  # Grafana credentials
  GRAFANA_PASSWORD: ""   # Replace with base64 encoded Grafana password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: learning-assistant
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  POSTGRES_PASSWORD: ""  # Replace with base64 encoded password
  POSTGRES_USER: bGVhcm5pbmdfdXNlcg==  # learning_user
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: learning-assistant
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: learning-assistant
type: Opaque
data:
  # Redis credentials (base64 encoded)
  REDIS_PASSWORD: ""     # Replace with base64 encoded password