apiVersion: v1
kind: Service
metadata:
  name: {{ include "learning-assistant.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "learning-assistant.labels" . | nindent 4 }}
    component: backend
  annotations:
    {{- include "learning-assistant.monitoringAnnotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  {{- if .Values.nginx.enabled }}
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  {{- end }}
  selector:
    {{- include "learning-assistant.selectorLabels" . | nindent 4 }}
    version: v1
  sessionAffinity: None
---
{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "learning-assistant.fullname" . }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "learning-assistant.labels" . | nindent 4 }}
    component: loadbalancer
  annotations:
    {{- with .Values.loadBalancer.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.loadBalancer.type }}
  ports:
  - port: 80
    targetPort: {{ .Values.nginx.enabled | ternary 80 .Values.service.targetPort }}
    protocol: TCP
    name: http
  - port: 443
    targetPort: {{ .Values.nginx.enabled | ternary 80 .Values.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    {{- include "learning-assistant.selectorLabels" . | nindent 4 }}
    version: v1
  loadBalancerSourceRanges:
  - 0.0.0.0/0
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "learning-assistant.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "learning-assistant.labels" . | nindent 4 }}
    component: backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "learning-assistant.selectorLabels" . | nindent 4 }}
    version: v1