# Development Secrets Configuration
# This file defines how secrets are managed in development environments

apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-config
  namespace: learning-assistant-dev
data:
  # Secrets Provider Configuration
  secrets-provider: "hashicorp-vault"
  vault-address: "http://vault-dev:8200"  # Local vault instance
  vault-namespace: "learning-assistant"
  vault-auth-method: "token"
  
  # Cache Configuration
  secrets-cache-ttl: "60"   # 1 minute for development
  secrets-rotation-enabled: "false"  # Disabled in development
  secrets-audit-enabled: "true"
  
  # Encryption Configuration
  encryption-algorithm: "aes-256-gcm"

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: learning-assistant-dev
type: Opaque
data:
  # Development vault token (base64 encoded)
  vault-token: "ZGV2LXRva2VuLWZvci10ZXN0aW5n"  # dev-token-for-testing
  
  # Development encryption key
  encryption-key: "ZGV2ZWxvcG1lbnQtZW5jcnlwdGlvbi1rZXktMzItY2hhcnM="  # development-encryption-key-32-chars

---
# Simple secret injection for development
apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
  namespace: learning-assistant-dev
type: Opaque
data:
  # Base64 encoded development secrets
  RESEND_API_KEY: "cmVfZGV2ZWxvcG1lbnRfa2V5XzEyMzQ1Njc4OTA="  # re_development_key_1234567890
  TAMBO_API_KEY: "dGFtYm9fZGV2ZWxvcG1lbnRfa2V5XzEyMzQ1Njc4OTA="  # tambo_development_key_1234567890
  LINGO_DEV_API_KEY: "bGluZ29fZGV2ZWxvcG1lbnRfa2V5XzEyMzQ1Njc4OTA="  # lingo_development_key_1234567890
  FIRECRAWL_API_KEY: "ZmlyZWNyYXdsX2Rldl9rZXlfMTIzNDU2Nzg5MA=="  # firecrawl_dev_key_1234567890
  BETTER_AUTH_SECRET: "YmV0dGVyX2F1dGhfZGV2X3NlY3JldF8xMjM0NTY3ODkwMTIzNDU2Nzg5MA=="  # better_auth_dev_secret_123456789012345678900
  JWT_SECRET: "and0X2Rldl9zZWNyZXRfMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw"  # jwt_dev_secret_123456789012345678901234567890
  JWT_REFRESH_SECRET: "and0X3JlZnJlc2hfZGV2X3NlY3JldF8xMjM0NTY3ODkwMTIzNDU2Nzg5MA=="  # jwt_refresh_dev_secret_123456789012345678900
  CSRF_SECRET: "Y3NyZl9kZXZfc2VjcmV0XzEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg="  # csrf_dev_secret_12345678901234567890123456780
  SUPABASE_SERVICE_ROLE_KEY: "c3VwYWJhc2VfZGV2X3NlcnZpY2Vfcm9sZV9rZXlfMTIzNDU2Nzg5MA=="  # supabase_dev_service_role_key_1234567890

---
# Development Deployment with simpler configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-assistant
  namespace: learning-assistant-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-assistant
  template:
    metadata:
      labels:
        app: learning-assistant
    spec:
      containers:
      - name: learning-assistant
        image: learning-assistant:dev
        ports:
        - containerPort: 3000
        env:
        # Application Configuration
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        
        # Secrets Provider Configuration
        - name: SECRETS_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-provider
        - name: SECRETS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: vault-address
        - name: SECRETS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: vault-namespace
        - name: SECRETS_CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-cache-ttl
        - name: SECRETS_ROTATION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-rotation-enabled
        
        # Vault Authentication
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-auth
              key: vault-token
        - name: SECRETS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: vault-auth
              key: encryption-key
        
        # Development-specific environment variables
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "debug"
        
        # Application Secrets
        envFrom:
        - secretRef:
            name: application-secrets
        
        # Development health checks (more lenient)
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        
        # Development resource limits (minimal)
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: learning-assistant-dev

---
# Development Service for easy access
apiVersion: v1
kind: Service
metadata:
  name: learning-assistant
  namespace: learning-assistant-dev
spec:
  selector:
    app: learning-assistant
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000  # Fixed port for development
  type: NodePort

---
# Vault development instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-dev
  namespace: learning-assistant-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-dev
  template:
    metadata:
      labels:
        app: vault-dev
    spec:
      containers:
      - name: vault
        image: vault:1.15.4
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "dev-token-for-testing"
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        - name: VAULT_LOG_LEVEL
          value: "debug"
        command:
        - vault
        - server
        - -dev
        - -dev-listen-address=0.0.0.0:8200
        - -log-level=debug
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  name: vault-dev
  namespace: learning-assistant-dev
spec:
  selector:
    app: vault-dev
  ports:
  - port: 8200
    targetPort: 8200
  type: ClusterIP