# Production Secrets Configuration
# This file defines how secrets are managed in production environments

apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-config
  namespace: learning-assistant
data:
  # Secrets Provider Configuration
  secrets-provider: "hashicorp-vault"
  vault-address: "https://vault.your-domain.com:8200"
  vault-namespace: "learning-assistant"
  vault-auth-method: "kubernetes"
  vault-role: "learning-assistant-prod"
  
  # Cache Configuration
  secrets-cache-ttl: "300"  # 5 minutes
  secrets-rotation-enabled: "true"
  secrets-audit-enabled: "true"
  
  # Encryption Configuration
  encryption-algorithm: "aes-256-gcm"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: learning-assistant
type: Opaque
data:
  # Base64 encoded Vault service account token
  # This should be managed by your secrets management system
  vault-token: ""  # Will be injected by CI/CD or external secrets operator
  
  # Encryption key for local secret encryption
  encryption-key: ""  # Will be injected by CI/CD or external secrets operator

---
# External Secrets Operator Configuration (if using ESO)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: learning-assistant
spec:
  provider:
    vault:
      server: "https://vault.your-domain.com:8200"
      path: "learning-assistant"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "learning-assistant-prod"
          serviceAccountRef:
            name: "vault-auth"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: learning-assistant
spec:
  refreshInterval: 300s  # 5 minutes
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: application-secrets
    creationPolicy: Owner
  data:
  - secretKey: RESEND_API_KEY
    remoteRef:
      key: resend-api-key
      property: value
  - secretKey: TAMBO_API_KEY
    remoteRef:
      key: tambo-api-key
      property: value
  - secretKey: LINGO_DEV_API_KEY
    remoteRef:
      key: lingo-dev-api-key
      property: value
  - secretKey: FIRECRAWL_API_KEY
    remoteRef:
      key: firecrawl-api-key
      property: value
  - secretKey: BETTER_AUTH_SECRET
    remoteRef:
      key: better-auth-secret
      property: value
  - secretKey: JWT_SECRET
    remoteRef:
      key: jwt-secret
      property: value
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: jwt-refresh-secret
      property: value
  - secretKey: CSRF_SECRET
    remoteRef:
      key: csrf-secret
      property: value
  - secretKey: SUPABASE_SERVICE_ROLE_KEY
    remoteRef:
      key: supabase-service-role-key
      property: value

---
# Deployment with secrets injection
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-assistant
  namespace: learning-assistant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learning-assistant
  template:
    metadata:
      labels:
        app: learning-assistant
      annotations:
        # Force pod restart when secrets change
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "learning-assistant-prod"
        vault.hashicorp.com/agent-inject-secret-config: "learning-assistant/config"
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: learning-assistant
        image: learning-assistant:latest
        ports:
        - containerPort: 3000
        env:
        # Application Configuration
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        
        # Secrets Provider Configuration
        - name: SECRETS_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-provider
        - name: SECRETS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: vault-address
        - name: SECRETS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: vault-namespace
        - name: SECRETS_CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-cache-ttl
        - name: SECRETS_ROTATION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-rotation-enabled
        - name: SECRETS_AUDIT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-audit-enabled
        
        # Vault Authentication
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-auth
              key: vault-token
        - name: SECRETS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: vault-auth
              key: encryption-key
        
        # Application Secrets (injected from External Secrets)
        envFrom:
        - secretRef:
            name: application-secrets
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        
        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

---
# Service Account for Vault authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: learning-assistant
  annotations:
    vault.hashicorp.com/role: "learning-assistant-prod"

---
# RBAC for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-role
  namespace: learning-assistant
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-binding
  namespace: learning-assistant
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: learning-assistant
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io

---
# Network Policy for secure communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-communication
  namespace: learning-assistant
spec:
  podSelector:
    matchLabels:
      app: learning-assistant
  policyTypes:
  - Egress
  egress:
  # Allow communication to Vault
  - to: []
    ports:
    - protocol: TCP
      port: 8200
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow communication to Kubernetes API
  - to: []
    ports:
    - protocol: TCP
      port: 443