# Staging Secrets Configuration
# This file defines how secrets are managed in staging environments

apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-config
  namespace: learning-assistant-staging
data:
  # Secrets Provider Configuration
  secrets-provider: "hashicorp-vault"
  vault-address: "https://vault-staging.your-domain.com:8200"
  vault-namespace: "learning-assistant"
  vault-auth-method: "kubernetes"
  vault-role: "learning-assistant-staging"
  
  # Cache Configuration
  secrets-cache-ttl: "300"  # 5 minutes
  secrets-rotation-enabled: "true"
  secrets-audit-enabled: "true"
  
  # Encryption Configuration
  encryption-algorithm: "aes-256-gcm"

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: learning-assistant-staging
type: Opaque
data:
  # Base64 encoded Vault service account token
  vault-token: ""  # Will be injected by CI/CD
  
  # Encryption key for local secret encryption
  encryption-key: ""  # Will be injected by CI/CD

---
# External Secrets Operator Configuration for Staging
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: learning-assistant-staging
spec:
  provider:
    vault:
      server: "https://vault-staging.your-domain.com:8200"
      path: "learning-assistant"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "learning-assistant-staging"
          serviceAccountRef:
            name: "vault-auth"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: learning-assistant-staging
spec:
  refreshInterval: 300s  # 5 minutes
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: application-secrets
    creationPolicy: Owner
  data:
  - secretKey: RESEND_API_KEY
    remoteRef:
      key: resend-api-key-staging
      property: value
  - secretKey: TAMBO_API_KEY
    remoteRef:
      key: tambo-api-key-staging
      property: value
  - secretKey: LINGO_DEV_API_KEY
    remoteRef:
      key: lingo-dev-api-key-staging
      property: value
  - secretKey: FIRECRAWL_API_KEY
    remoteRef:
      key: firecrawl-api-key-staging
      property: value
  - secretKey: BETTER_AUTH_SECRET
    remoteRef:
      key: better-auth-secret-staging
      property: value
  - secretKey: JWT_SECRET
    remoteRef:
      key: jwt-secret-staging
      property: value
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: jwt-refresh-secret-staging
      property: value
  - secretKey: CSRF_SECRET
    remoteRef:
      key: csrf-secret-staging
      property: value
  - secretKey: SUPABASE_SERVICE_ROLE_KEY
    remoteRef:
      key: supabase-service-role-key-staging
      property: value

---
# Staging Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-assistant
  namespace: learning-assistant-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-assistant
  template:
    metadata:
      labels:
        app: learning-assistant
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "learning-assistant-staging"
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: learning-assistant
        image: learning-assistant:staging
        ports:
        - containerPort: 3000
        env:
        # Application Configuration
        - name: NODE_ENV
          value: "staging"
        - name: PORT
          value: "3000"
        
        # Secrets Provider Configuration
        - name: SECRETS_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-provider
        - name: SECRETS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: vault-address
        - name: SECRETS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: vault-namespace
        - name: SECRETS_CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: secrets-cache-ttl
        
        # Vault Authentication
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-auth
              key: vault-token
        - name: SECRETS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: vault-auth
              key: encryption-key
        
        # Application Secrets
        envFrom:
        - secretRef:
            name: application-secrets
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        
        # Resource limits (lower for staging)
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: learning-assistant-staging
  annotations:
    vault.hashicorp.com/role: "learning-assistant-staging"